FROM python
WORKDIR /home
COPY LoremServer /home/LoremServer
COPY python.sh /home/
RUN pip3 install django -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install wordcloud -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install pyjwt -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install redis -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install pymysql -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install pymongo -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install pandas -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install django_redis -i https://pypi.tuna.tsinghua.edu.cn/simple
